# Generated by Django 3.1.7 on 2021-04-01 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_is_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_member',
        ),
    ]
