# Generated by Django 3.1.7 on 2021-02-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_searchable',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
