# Generated by Django 3.1.7 on 2021-02-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_is_searchable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_searchable',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
