# Generated by Django 3.1.7 on 2021-02-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210224_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_searchable',
        ),
        migrations.AddField(
            model_name='product',
            name='is_searchable',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
