# Generated by Django 3.1.7 on 2021-03-04 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_ticket_is_presale'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='code',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
