# Generated by Django 3.1.7 on 2021-03-05 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210304_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.city'),
        ),
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_presale',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.section'),
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
