# Generated by Django 3.1.7 on 2021-03-31 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210305_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_membership',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
