# Generated by Django 3.1.7 on 2021-03-31 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_is_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_membership',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
